// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography';
import Hero from './Hero';
import Skills from './Skills';

export {
	Biography,
	Hero,
	Skills,
};

export const components = {
	biography: Biography,
	hero: Hero,
	skills: Skills,
};
